/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppContextMenu: typeof import('./components/AppContextMenu.vue')['default']
    AppIcon: typeof import('./components/icons/AppIcon.vue')['default']
    ApplicationWindow: typeof import('./components/layout/ApplicationWindow.vue')['default']
    DesktopHeader: typeof import('./components/layout/DesktopHeader.vue')['default']
    DesktopLayout: typeof import('./components/layout/DesktopLayout.vue')['default']
    MonacoEditor: typeof import('./components/editor/MonacoEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecLabActionMenu: typeof import('./components/ui/SecLabActionMenu.vue')['default']
    SecLabAlert: typeof import('./components/ui/SecLabAlert.vue')['default']
    SecLabBreadcrumb: typeof import('./components/ui/SecLabBreadcrumb.vue')['default']
    SecLabBreadcrumbItem: typeof import('./components/ui/SecLabBreadcrumbItem.vue')['default']
    SecLabButton: typeof import('./components/ui/SecLabButton.vue')['default']
    SecLabCard: typeof import('./components/ui/SecLabCard.vue')['default']
    SecLabCheckbox: typeof import('./components/ui/SecLabCheckbox.vue')['default']
    SecLabDateTimeRangePicker: typeof import('./components/ui/SecLabDateTimeRangePicker.vue')['default']
    SecLabDescriptions: typeof import('./components/ui/SecLabDescriptions.vue')['default']
    SecLabDialog: typeof import('./components/ui/SecLabDialog.vue')['default']
    SecLabDrawer: typeof import('./components/ui/SecLabDrawer.vue')['default']
    SecLabEmpty: typeof import('./components/ui/SecLabEmpty.vue')['default']
    SecLabFormItem: typeof import('./components/ui/SecLabFormItem.vue')['default']
    SecLabIcon: typeof import('./components/icons/SecLabIcon.vue')['default']
    SecLabInput: typeof import('./components/ui/SecLabInput.vue')['default']
    SecLabLoading: typeof import('./components/ui/SecLabLoading.vue')['default']
    SecLabMenu: typeof import('./components/ui/SecLabMenu.vue')['default']
    SecLabModal: typeof import('./components/ui/SecLabModal.vue')['default']
    SecLabPagination: typeof import('./components/ui/SecLabPagination.vue')['default']
    SecLabSelect: typeof import('./components/ui/SecLabSelect.vue')['default']
    SecLabSelectionBar: typeof import('./components/ui/SecLabSelectionBar.vue')['default']
    SecLabSwitch: typeof import('./components/ui/SecLabSwitch.vue')['default']
    SecLabTable: typeof import('./components/ui/SecLabTable.vue')['default']
    SecLabTabs: typeof import('./components/ui/SecLabTabs.vue')['default']
    SecLabTag: typeof import('./components/ui/SecLabTag.vue')['default']
    SecLabToast: typeof import('./components/ui/SecLabToast.vue')['default']
    SecLabTooltip: typeof import('./components/ui/SecLabTooltip.vue')['default']
  }
}
